version: "3.4"

networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true

services:
  transmission:
    image: linuxserver/transmission:amd64-latest
    networks:
      - net
      - proxynetwork
    environment:
      - TZ=Europe/Paris
      - USER=admin
      - PASS=WR9j7fv6D
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/downloads:/downloads
      - ${PWD}/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transmission.rule=Host(`transmission.traefik.me`)"
        - "traefik.http.routers.transmission-tls.tls.domains[0].main=transmission.traefik.me"
        - "traefik.http.routers.transmission-tls.tls.domains[0].sans=transmission-*.traefik.me"
        - "traefik.http.services.transmission.loadbalancer.server.port=9091"
